#!/bin/bash

## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

echo "$0: $$"

trap "handler" TERM INT

handler() {
   echo "$0: signal recieved, exiting"
   exit 0
}

while true; do
   sleep 60 &
   wait $!
done
